name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Setup key
      - run: mkdir "$HOME/.ssh"
      - run: echo "{{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Build
      - run: |
         docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
         docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest
     # Deploy
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: docker/metadata-action@v1
          
      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      #- run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" docker build . -t app
      #- run: cd dist && rsync -e "ssh -i $HOME/.ssh/key -o"
