name: Docekr

on:
  push:
    branches:
      - master
jobs:
  run-tests:
    name: Run test
    runs-on: ubuntu-latest
    container:
      image: app:latest
      volumes:
        - ${{ github.workspace }}:/app
  steps:
    uses: actions/checkout@v2
